#!/bin/bash

# create a new Zettelkasten note and open it in vim

cmd=vim

if [[ $DISPLAY ]]; then
    cmd=gvim
fi

filename=$(date +%Y%m%d%H%M%S).md

cat <<EOF >> $filename
# $filename

tags: ``
EOF

"$cmd" -c ":execute 'norm gg'" -c "startinsert!" $filename
