#!/bin/bash

# create a new Zettelkasten note and open it in vim

cmd=vim

if [[ $DISPLAY ]]; then
    cmd=gvim
fi

now=$(date +%Y%m%d%H%M%S)
filename="$now.md"

cat <<EOF >> $filename
# $now

tags: ``
EOF

"$cmd" -c ":execute 'norm gg'" -c "startinsert!" $filename
