#!/bin/bash

# search for a string in Zettelkasten notes, using ripgrep
# show search results in fzf with preview
# open selected note in vim

# usage: zks STRING

cmd=vim

if [[ $DISPLAY ]]; then
    cmd=gvim
fi

selected=$( rg -l "$1" | fzf --preview="cat {} | sed 's/$1/\\\\033[0\;31m$1\\\\033[0m/g' | xargs -0 printf " )
if [[ ! -z "$selected" ]]; then
    "$cmd" "$selected"
fi
